In [2]:
import os
import time
import random
import warnings

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from lxml import etree # type: ignore <- pylance milně hlásí chybu
from pathlib import Path
import time
import sys
import polars as pl
import polars.selectors as cs
import json
import pickle
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from ydata_profiling import ProfileReport

from utils import *
from schemas import *
from processing import *

pl.Config.set_tbl_cols(-1)
os.chdir(r'E:\CVUT_BAP')
SEED=42

# STARE

In [ ]:
short_display(df_mereni.filter(pl.col('CisloProtokolu') == 'CZ-540308-24-02-0512'))

NameError: name 'df_mereni' is not defined

In [ ]:
cislo_protokolu_technicka = set(df_technicka.select(pl.col('Emise_CisloProtokolu').str.replace(r'^CZ-(0+)(\d+)', r'CZ-${2}'))['Emise_CisloProtokolu'])
cislo_protokolu_mereni = set(df_mereni.select(pl.col('CisloProtokolu').str.replace(r'^CZ-(0+)(\d+)', r'CZ-${2}'))['CisloProtokolu'])
cislo_protokolu_mereni - cislo_protokolu_technicka

{'CZ-120902-20-07-0174', 'CZ-410432-20-08-0152'}

In [ ]:
df_mereni['Vozidlo_Palivo'].value_counts()

shape: (5, 2)
┌────────────────┬────────┐
│ Vozidlo_Palivo ┆ count  │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ BNB            ┆ 8      │
│ NM             ┆ 685379 │
│ N              ┆ 148321 │
│ null           ┆ 1216   │
│ BA             ┆ 2      │
└────────────────┴────────┘

In [ ]:
cols_akcelerace = ['Nafta_Mereni0_CasAkcelerace_Hodnota', 'Nafta_Mereni1_CasAkcelerace_Hodnota', 'Nafta_Mereni2_CasAkcelerace_Hodnota', 'Nafta_Mereni3_CasAkcelerace_Hodnota']
redundant_nafta = df_mereni.filter(pl.all_horizontal(pl.col(cols_akcelerace).is_not_null())).group_by(cols_akcelerace).len(name='group_size').sort('group_size', descending=True)
redundant_nafta

shape: (2_183_134, 5)
┌─────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────┐
│ Nafta_Mereni0_CasAk ┆ Nafta_Mereni1_CasAk ┆ Nafta_Mereni2_CasA ┆ Nafta_Mereni3_CasA ┆ group_size │
│ celerace_Ho…        ┆ celerace_Ho…        ┆ kcelerace_Ho…      ┆ kcelerace_Ho…      ┆ ---        │
│ ---                 ┆ ---                 ┆ ---                ┆ ---                ┆ u32        │
│ f32                 ┆ f32                 ┆ f32                ┆ f32                ┆            │
╞═════════════════════╪═════════════════════╪════════════════════╪════════════════════╪════════════╡
│ 1.88                ┆ 1.84                ┆ 1.78               ┆ 1.7                ┆ 1596       │
│ 1.8                 ┆ 1.67                ┆ 1.62               ┆ 1.63               ┆ 989        │
│ 0.01                ┆ 0.01                ┆ 0.01               ┆ 0.01               ┆ 940        │
│ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                ┆ 707        │
│ 0.49                ┆ 0.76                ┆ 0.82               ┆ 1.03               ┆ 526        │
│ …                   ┆ …                   ┆ …                  ┆ …                  ┆ …          │
│ 0.91                ┆ 1.4                 ┆ 1.79               ┆ 1.82               ┆ 1          │
│ 1.7                 ┆ 1.89                ┆ 1.97               ┆ 1.34               ┆ 1          │
│ 2.73                ┆ 2.93                ┆ 3.13               ┆ 2.87               ┆ 1          │
│ 2.35                ┆ 2.53                ┆ 2.13               ┆ 2.09               ┆ 1          │
│ 1.68                ┆ 1.64                ┆ 1.31               ┆ 1.5                ┆ 1          │
└─────────────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────┘

In [ ]:
substr = 'visualni'
for column in df.columns:
    if substr.lower() in column.lower():
        print(column, end=', ')

Vysledek_VisualniKontrola,

# Nove

In [6]:
parsed = os.listdir('kod/data/data_z_mericich_pristroju/parquet/mereni')
len(parsed)

2442

In [5]:
mereni_2020_path = Path('../zdroje/ANALYZA DAT MERENI SME z ISTP/2020/sme')
csv_files = []
for f in mereni_2020_path.iterdir():
    if f.stem[-1: ] == 'V':
        csv_files.append(f)


data_frames = []
for csv_file in csv_files:
    data_frames.append(pd.read_csv(csv_file, delimiter=';'))

df = pd.concat(data_frames)

C:\Users\adamp\AppData\Local\Temp\ipykernel_23496\3016768282.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(data_frames)

In [28]:
# print(list(df.columns))

In [10]:
df[np.all(df[['D11-AccTime', 'D12-AccTime', 'D13-AccTime', 'D14-AccTime']].values == [1.88, 1.84, 1.78, 1.70], axis=1)][['SME', 'DateTime', 'D11-AccTime','D12-AccTime', 'D13-AccTime', 'D14-AccTime', 'VIN']]

,SME,DateTime,D11-AccTime,D12-AccTime,D13-AccTime,D14-AccTime,VIN
73,540514.0,2020-01-03T06:40:00,1.88,1.84,1.78,1.7,VF3GJRHYK95052878
182,540514.0,2020-01-06T10:10:00,1.88,1.84,1.78,1.7,ZFA19200000105264
204,540514.0,2020-01-06T10:20:00,1.88,1.84,1.78,1.7,WBAAL71020KE07146
207,540514.0,2020-01-06T10:31:00,1.88,1.84,1.78,1.7,YV1SW720211084029
221,540514.0,2020-01-06T10:31:00,1.88,1.84,1.78,1.7,YV1SW720211084029
...,...,...,...,...,...,...,...
18378,540514.0,2020-08-28T09:51:00,1.88,1.84,1.78,1.7,WDB6013671P076453
18427,540514.0,2020-08-31T06:20:00,1.88,1.84,1.78,1.7,WVWZZZ1HZXK024417
18429,540514.0,2020-08-31T06:11:00,1.88,1.84,1.78,1.7,TMBBG41U432699607
18454,540514.0,2020-08-31T08:17:00,1.88,1.84,1.78,1.7,WVWZZZ3BZ1E253013
18518,540514.0,2020-08-31T13:42:00,1.88,1.84,1.78,1.7,JMBLYV78W2J002607

In [9]:

vin = "WVWZZZ3BZ1E253013"

# lazy scan, filter only VIN matches
df = (
    pl.scan_csv(
        "../zdroje/RSV_vypis_vozidel_20251101.csv",
        infer_schema_length=1000,
        truncate_ragged_lines=True,
        ignore_errors=True,
        quote_char=None
    )
    .filter(pl.any_horizontal(pl.all().cast(pl.Utf8).str.contains(vin)))
    .collect()
)

df.shape[0] > 0  # True if VIN exists

True

In [10]:
df

shape: (1, 98)
┌────────────┬────────────┬───────────┬───────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ Datum 1    ┆ Datum 1    ┆ ZTP       ┆ ES EU     ┆ … ┆ Výška do ┆ Typ kód ┆ RM zániku ┆ Stupeň    │
│ registrace ┆ registrace ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---     ┆ ---       ┆ autonomit │
│ ---        ┆ v ČR       ┆ str       ┆ str       ┆   ┆ str      ┆ str     ┆ str       ┆ y vozidla │
│ str        ┆ ---        ┆           ┆           ┆   ┆          ┆         ┆           ┆ ---       │
│            ┆ str        ┆           ┆           ┆   ┆          ┆         ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 11.04.2001 ┆ 25.10.2012 ┆ 3483-137- ┆ e1*98/14* ┆ … ┆ False    ┆ null    ┆ 100       ┆ null      │
│            ┆            ┆ 00        ┆ 0157*     ┆   ┆          ┆         ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴──────────┴─────────┴───────────┴───────────┘

## Nahodny maly vzorek dat

In [3]:
def get_sample(path, schema):
    files = [f for f in path.iterdir()]
    random.seed(SEED)
    random.shuffle(files)
    files = files[:50]

    df = pl.DataFrame()
    for file in files:
        df = pl.concat([df, pl.read_parquet(file, schema=schema)])
    return df

In [5]:
df = get_sample(Path('kod/data/prohlidky_vozidel_stk_a_sme/parquet/prohlidky'), prohlidky_schema)
# df = get_sample(Path('kod/data/data_z_mericich_pristroju/parquet/nafta_osobni'), nafta_schema)
short_display(df)

(1001015, 52)

,CisloProtokolu,DatumProhlidky,DruhProhlidky,RozsahProhlidky,Prohlidka_OdpovednaOsoba,Prohlidka_Stanice_Cislo,Prohlidka_Stanice_Kraj,Prohlidka_Stanice_ORP,Prohlidka_Stanice_Obec,Prohlidka_Zahajeni,...,Adr_KodCisterny,Adr_CisloOsvedceni,Adr_ZavadyText,Adr_Poznamka,Tsk_OdpovednaOsoba,Vysledek_Odometr,Vysledek_Poznamka,Vysledek_DatumPristiProhlidky,Vysledek_NalepkaVylepena,Vysledek_Celkovy
0,CZ-3239-24-12-0248,2024-12-06,Opakovaná,Částečný,23441,3239,Středočeský kraj,Rakovník,Nové Strašecí,2024-12-06T16:57:09.1770000+01:00,...,None,None,None,None,None,None,None,2026-11-22,true,1
1,CZ-3609-24-12-0612,2024-12-06,Opakovaná,Částečný,5489,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T17:12:58.7870000+01:00,...,None,None,None,None,None,138316,None,2026-11-13,true,1
2,CZ-3609-24-12-0619,2024-12-06,Pravidelná,Plný,5489,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T18:16:38.7830000+01:00,...,None,None,None,None,None,189341,None,2026-12-06,true,1
3,CZ-3239-24-12-0254,2024-12-06,Pravidelná,Plný,23441,3239,Středočeský kraj,Rakovník,Nové Strašecí,2024-12-06T18:23:24.1270000+01:00,...,None,None,None,None,None,403246,None,2025-12-06,true,1
4,CZ-3609-24-12-0621,2024-12-06,Pravidelná,Plný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T18:35:33.4770000+01:00,...,None,None,None,None,None,241433,None,2025-01-05,true,2
5,CZ-3630-24-12-0239,2024-12-06,Pravidelná,Plný,47793,3630,Královéhradecký kraj,Hradec Králové,Nechanice,2024-12-06T18:40:23.4070000+01:00,...,None,None,None,None,None,100137,None,2026-12-06,true,1
6,CZ-3849-24-12-0212,2024-12-06,Pravidelná,Plný,10513,3849,Moravskoslezský kraj,Frýdek-Místek,Frýdek-Místek,2024-12-06T18:42:29.0930000+01:00,...,None,None,None,None,None,77531,None,2026-12-06,true,1
7,CZ-3609-24-12-0623,2024-12-06,Pred registrací,Plný,2649,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T18:42:33.1770000+01:00,...,None,None,None,None,None,279326,None,2026-12-06,false,1
8,CZ-3730-24-12-0198,2024-12-06,Pravidelná,Plný,27773,3730,Kraj Vysočina,Moravské Budějovice,Moravské Budějovice,2024-12-06T18:43:27.6600000+01:00,...,None,None,None,None,None,237375,None,2026-12-06,true,1
9,CZ-3239-24-12-0255,2024-12-06,Pravidelná,Plný,23441,3239,Středočeský kraj,Rakovník,Nové Strašecí,2024-12-06T18:46:46.6670000+01:00,...,None,None,None,None,None,63303,None,2026-12-06,true,1
10,CZ-3415-24-12-0528,2024-12-06,Pred registrací,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T18:50:07.3430000+01:00,...,None,None,None,None,None,253620,None,2026-12-06,false,1
11,CZ-3415-24-12-0529,2024-12-06,Pravidelná,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T18:50:54.2000000+01:00,...,None,None,None,None,None,74620,None,2026-12-06,true,1
12,CZ-3609-24-12-0624,2024-12-06,Opakovaná,Částečný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:00:48.9070000+01:00,...,None,None,None,None,None,249958,None,2026-11-27,true,1
13,CZ-3415-24-12-0530,2024-12-06,Pravidelná,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:01:59.9970000+01:00,...,None,None,None,None,None,10757,None,2026-12-06,true,1
14,CZ-3415-24-12-0531,2024-12-06,Pravidelná,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:10:38.9730000+01:00,...,None,None,None,None,None,272405,None,2025-01-05,true,2
15,CZ-3609-24-12-0625,2024-12-06,Pravidelná,Plný,2649,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:14:34.2300000+01:00,...,None,None,None,None,None,199163,None,2026-12-06,true,1
16,CZ-3415-24-12-0532,2024-12-06,Pravidelná,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:17:17.9630000+01:00,...,None,None,None,None,None,240176,None,2026-12-06,true,1
17,CZ-3213-24-12-0246,2024-12-06,Pravidelná,Plný,82185,3213,Středočeský kraj,Brandýs nad Labem-Stará Boleslav,Brandýs nad Labem-Stará Boleslav,2024-12-06T19:17:30.1100000+01:00,...,None,None,None,None,None,59904,None,2026-12-06,true,1
18,CZ-3849-24-12-0213,2024-12-06,Pravidelná,Plný,10513,3849,Moravskoslezský kraj,Frýdek-Místek,Frýdek-Místek,2024-12-06T19:20:09.0230000+01:00,...,None,None,None,None,None,124128,None,2026-12-06,true,1
19,CZ-3609-24-12-0626,2024-12-06,Pravidelná,Plný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:21:16.4400000+01:00,...,None,None,None,None,None,261850,None,2026-12-06,true,1
20,CZ-3415-24-12-0533,2024-12-06,Pravidelná,Plný,84839,3415,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:29:49.6130000+01:00,...,None,None,None,None,None,138866,None,2026-12-06,true,1
21,CZ-3609-24-12-0627,2024-12-06,Pravidelná,Plný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:47:57.1570000+01:00,...,None,None,None,None,None,51766,None,2026-12-06,true,1
22,CZ-3849-24-12-0214,2024-12-06,Evidencní kontrola,Plný,10513,3849,Moravskoslezský kraj,Frýdek-Místek,Frýdek-Místek,2024-12-06T19:48:33.0600000+01:00,...,None,None,None,None,None,2671,None,None,false,1
23,CZ-3609-24-12-0628,2024-12-06,Pravidelná,Plný,2649,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:51:07.2630000+01:00,...,None,None,None,None,None,323179,None,2026-12-06,true,1
24,CZ-3849-24-12-0215,2024-12-06,Pravidelná,Plný,12539,3849,Moravskoslezský kraj,Frýdek-Místek,Frýdek-Místek,2024-12-06T20:15:34.4230000+01:00,...,None,None,None,None,None,105950,None,None,false,3
25,CZ-3609-24-12-0629,2024-12-06,Pravidelná,Plný,5489,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T20:18:26.9230000+01:00,...,None,None,None,None,None,77210,None,2026-12-06,true,1
26,CZ-3609-24-12-0630,2024-12-06,Opakovaná,Částečný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T20:30:00.6200000+01:00,...,None,None,None,None,None,102686,None,2026-11-22,true,1
27,CZ-3609-24-12-0631,2024-12-06,Pravidelná,Plný,2649,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T20:31:48.8000000+01:00,...,None,None,None,None,None,209998,None,2026-12-06,true,1
28,CZ-3609-24-12-0632,2024-12-06,Pravidelná,Plný,111369,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T20:37:35.8200000+01:00,...,None,None,None,None,None,155945,None,2026-12-06,true,1
29,CZ-3609-24-12-0633,2024-12-06,Pravidelná,Plný,2649,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T21:01:43.9870000+01:00,...,None,None,None,None,None,384601,None,2026-12-06,true,1
30,CZ-3609-24-12-0583,2024-12-06,TSK - Opakovaná po DN,Plný,5489,3609,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T14:35:39.7600000+01:00,...,None,None,None,None,None,177994,None,2025-06-14,false,1
31,CZ-7705-24-12-0012,2024-12-06,Technická silniční kontrola,Částečný,84345,7705,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T22:37:36.4270000+01:00,...,None,None,None,None,84345,None,None,None,false,1
32,CZ-7701-24-12-0110,2024-12-06,Technická silniční kontrola,Částečný,18253,7701,Hlavní město Praha,Hlavní město Praha,Praha,2024-12-06T21:29:34.3500000+01:00,...,None,None,None,None,18253,38734,None,None,false,1
33,CZ-7704-24-12-0189,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T20:36:37.2500000+01:00,...,None,None,None,None,110835,None,None,None,false,1
34,CZ-7704-24-12-0190,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T22:34:23.4530000+01:00,...,None,None,None,None,110835,1001157,None,None,false,1
35,CZ-7704-24-12-0191,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T22:38:24.3700000+01:00,...,None,None,None,None,110835,None,None,None,false,1
36,CZ-7704-24-12-0194,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T19:27:08.9100000+01:00,...,None,None,None,None,110835,None,None,None,false,1
37,CZ-7704-24-12-0195,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T19:30:59.7730000+01:00,...,None,None,None,None,110835,None,None,None,false,1
38,CZ-7704-24-12-0196,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T19:20:19.3630000+01:00,...,None,None,None,None,110835,446976,None,None,false,1
39,CZ-7704-24-12-0197,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T19:20:09.6500000+01:00,...,None,None,None,None,110835,None,None,None,false,1
40,CZ-7704-24-12-0198,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T20:00:13.8270000+01:00,...,None,None,None,None,110835,957294,None,None,false,1
41,CZ-7704-24-12-0199,2024-12-06,Technická silniční kontrola,Částečný,110835,7704,Ústecký kraj,Ústí nad Labem,Ústí nad Labem,2024-12-06T20:25:40.3800000+01:00,...,None,None,None,None,110835,774924,None,None,false,3
42,CZ-420932-24-12-0161,2024-12-06,Pravidelná,None,8691,420932,Středočeský kraj,Brandýs nad Labem-Stará Boleslav,Brandýs nad Labem-Stará Boleslav,2024-12-06T18:59:09.2400000+01:00,...,None,None,None,None,None,59904,None,2026-12-06,None,1
43,CZ-440709-24-12-0356,2024-12-06,Pravidelná,None,37145,440709,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T18:59:44.5330000+01:00,...,None,None,None,None,None,240176,None,2026-12-06,None,1
44,CZ-460214-24-12-0439,2024-12-06,Pravidelná,None,37763,460214,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:04:14.6570000+01:00,...,None,None,None,None,None,261850,None,2026-12-06,None,1
45,CZ-440709-24-12-0357,2024-12-06,Pravidelná,None,34843,440709,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:10:40.2330000+01:00,...,None,None,None,None,None,138866,None,2026-12-06,None,1
46,CZ-440709-24-12-0358,2024-12-06,Pravidelná,None,37145,440709,Plzeňský kraj,Kralovice,Rybnice,2024-12-06T19:19:53.7630000+01:00,...,None,None,None,None,None,284665,None,2025-12-06,None,1
47,CZ-460214-24-12-0440,2024-12-06,Pravidelná,None,82881,460214,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:33:14.4930000+01:00,...,None,None,None,None,None,51766,None,2026-12-06,None,1
48,CZ-480238-24-12-0138,2024-12-06,Pravidelná,None,12539,480238,Moravskoslezský kraj,Frýdek-Místek,Frýdek-Místek,2024-12-06T19:46:29.5500000+01:00,...,None,None,None,None,None,105950,None,2026-12-06,None,1
49,CZ-460214-24-12-0441,2024-12-06,Pravidelná,None,37931,460214,Královéhradecký kraj,Hradec Králové,Hradec Králové,2024-12-06T19:53:43.8470000+01:00,...,None,None,None,None,None,77210,DEKRA DATA\nTDP-E04,2026-12-06,None,1

In [7]:
df['DruhProhlidky'].value_counts(sort=True)

shape: (16, 2)
┌─────────────────────────────────┬────────┐
│ DruhProhlidky                   ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Pravidelná                      ┆ 838439 │
│ Evidencní kontrola              ┆ 97366  │
│ Opakovaná                       ┆ 32107  │
│ Pred registrací                 ┆ 23448  │
│ Technická silniční kontrola     ┆ 3265   │
│ …                               ┆ …      │
│ TSK - Opakovaná po DN           ┆ 107    │
│ Pred schvál. tech. zpusob. voz… ┆ 48     │
│ ADR - opakovaná                 ┆ 35     │
│ Narízená technická prohlídka    ┆ 17     │
│ Historického vozidla - opakova… ┆ 9      │
└─────────────────────────────────┴────────┘