In [2]:
import os
import polars as pl
from pathlib import Path
import pandas as pd
import numpy as np
from lxml import etree # type: ignore <- pylance milně hlásí chybu
import random


os.chdir(r'E:\CVUT_BAP')

In [6]:
parsed = os.listdir('kod/data/data_z_mericich_pristroju/parquet/mereni')
len(parsed)

2442

In [5]:
mereni_2020_path = Path('../zdroje/ANALYZA DAT MERENI SME z ISTP/2020/sme')
csv_files = []
for f in mereni_2020_path.iterdir():
    if f.stem[-1: ] == 'V':
        csv_files.append(f)


data_frames = []
for csv_file in csv_files:
    data_frames.append(pd.read_csv(csv_file, delimiter=';'))

df = pd.concat(data_frames)

C:\Users\adamp\AppData\Local\Temp\ipykernel_23496\3016768282.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(data_frames)

In [28]:
# print(list(df.columns))

In [10]:
df[np.all(df[['D11-AccTime', 'D12-AccTime', 'D13-AccTime', 'D14-AccTime']].values == [1.88, 1.84, 1.78, 1.70], axis=1)][['SME', 'DateTime', 'D11-AccTime','D12-AccTime', 'D13-AccTime', 'D14-AccTime', 'VIN']]

,SME,DateTime,D11-AccTime,D12-AccTime,D13-AccTime,D14-AccTime,VIN
73,540514.0,2020-01-03T06:40:00,1.88,1.84,1.78,1.7,VF3GJRHYK95052878
182,540514.0,2020-01-06T10:10:00,1.88,1.84,1.78,1.7,ZFA19200000105264
204,540514.0,2020-01-06T10:20:00,1.88,1.84,1.78,1.7,WBAAL71020KE07146
207,540514.0,2020-01-06T10:31:00,1.88,1.84,1.78,1.7,YV1SW720211084029
221,540514.0,2020-01-06T10:31:00,1.88,1.84,1.78,1.7,YV1SW720211084029
...,...,...,...,...,...,...,...
18378,540514.0,2020-08-28T09:51:00,1.88,1.84,1.78,1.7,WDB6013671P076453
18427,540514.0,2020-08-31T06:20:00,1.88,1.84,1.78,1.7,WVWZZZ1HZXK024417
18429,540514.0,2020-08-31T06:11:00,1.88,1.84,1.78,1.7,TMBBG41U432699607
18454,540514.0,2020-08-31T08:17:00,1.88,1.84,1.78,1.7,WVWZZZ3BZ1E253013
18518,540514.0,2020-08-31T13:42:00,1.88,1.84,1.78,1.7,JMBLYV78W2J002607

In [9]:

vin = "WVWZZZ3BZ1E253013"

# lazy scan, filter only VIN matches
df = (
    pl.scan_csv(
        "../zdroje/RSV_vypis_vozidel_20251101.csv",
        infer_schema_length=1000,
        truncate_ragged_lines=True,
        ignore_errors=True,
        quote_char=None
    )
    .filter(pl.any_horizontal(pl.all().cast(pl.Utf8).str.contains(vin)))
    .collect()
)

df.shape[0] > 0  # True if VIN exists

True

In [10]:
df

shape: (1, 98)
┌────────────┬────────────┬───────────┬───────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ Datum 1    ┆ Datum 1    ┆ ZTP       ┆ ES EU     ┆ … ┆ Výška do ┆ Typ kód ┆ RM zániku ┆ Stupeň    │
│ registrace ┆ registrace ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---     ┆ ---       ┆ autonomit │
│ ---        ┆ v ČR       ┆ str       ┆ str       ┆   ┆ str      ┆ str     ┆ str       ┆ y vozidla │
│ str        ┆ ---        ┆           ┆           ┆   ┆          ┆         ┆           ┆ ---       │
│            ┆ str        ┆           ┆           ┆   ┆          ┆         ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 11.04.2001 ┆ 25.10.2012 ┆ 3483-137- ┆ e1*98/14* ┆ … ┆ False    ┆ null    ┆ 100       ┆ null      │
│            ┆            ┆ 00        ┆ 0157*     ┆   ┆          ┆         ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴──────────┴─────────┴───────────┴───────────┘