In [1]:
import os
import time
import random
import warnings

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from lxml import etree # type: ignore <- pylance milně hlásí chybu
from pathlib import Path
import time
import sys
import polars as pl
import polars.selectors as cs
import json
import pickle
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from ydata_profiling import ProfileReport

current_dir = Path(__file__).resolve().parent if "__file__" in locals() else Path.cwd()
sys.path.append(str(current_dir.parent))
from utils import *
from schemas import *

pl.Config.set_tbl_cols(-1)
os.chdir(r'E:\CVUT_BAP')
SEED=42

# Načtení dat

In [4]:
df = pl.read_parquet(r'kod\data\extracted\data_z_mericich_pristroju\parquet', schema=mereni_schema)
describe(df)

shape: (1, 321)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Cis ┆ Dat ┆ Sta ┆ Zah ┆ Uko ┆ Odp ┆ Pro ┆ Pro ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Poz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Voz ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Vys ┆ Pri ┆ Emi ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Zav ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Obd ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Ben ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Naf ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply ┆ Ply │
│ loP ┆ umP ┆ nic ┆ aje ┆ nce ┆ ove ┆ hli ┆ hli ┆ ici ┆ ici ┆ ici ┆ ici ┆ ici ┆ nam ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ idl ┆ led ┆ led ┆ led ┆ led ┆ led ┆ led ┆ led ┆ sti ┆ sni ┆ _Ko ┆ _Vi ┆ _Po ┆ _Vz ┆ _Ca ┆ _Ko ┆ _Vy ┆ ady ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ _Re ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ zin ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ n_P ┆ n_P ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_O ┆ n_N ┆ n_N ┆ n_N ┆ n_N │
│ rot ┆ roh ┆ eCi ┆ ni  ┆ ni  ┆ dna ┆ dka ┆ dka ┆ Pri ┆ Pri ┆ Pri ┆ Pri ┆ Pri ┆ ky  ┆ o_V ┆ o_Z ┆ o_O ┆ o_T ┆ o_C ┆ o_O ┆ o_R ┆ o_D ┆ o_P ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ ek_ ┆ Pro ┆ Sys ┆ mun ┆ n   ┆ cet ┆ dal ┆ sDt ┆ ntr ┆ pis ┆ --- ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ adi ┆ _Pa ┆ _Po ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Pal ┆ Poc ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ Mer ┆ ali ┆ oce ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ adr ┆ adr ┆ adr ┆ adr │
│ oko ┆ lid ┆ slo ┆ --- ┆ --- ┆ Oso ┆ _Ci ┆ _Da ┆ str ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ in  ┆ nac ┆ bch ┆ ypM ┆ isl ┆ dom ┆ okV ┆ atu ┆ ali ┆ Vis ┆ Rea ┆ Rid ┆ Rid ┆ Mil ┆ Tes ┆ Vyh ┆ hli ┆ tem ┆ ika ┆ --- ┆ Dtc ┆ eno ┆ c   ┆ ola ┆ Dtc ┆ lis ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ nes ┆ liv ┆ cet ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ ack ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ ivo ┆ etV ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ eni ┆ vo  ┆ tVy ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyV ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ kyZ ┆ z_V ┆ z_H ┆ z_Z ┆ z_K │
│ lu  ┆ ky  ┆ --- ┆ str ┆ str ┆ ba  ┆ slo ┆ tum ┆ oj_ ┆ oj_ ┆ oj_ ┆ oj_ ┆ oj_ ┆ lis ┆ --- ┆ ka  ┆ odn ┆ oto ┆ oMo ┆ ete ┆ yro ┆ mPr ┆ vo  ┆ ual ┆ din ┆ ici ┆ ici ┆ --- ┆ nos ┆ ovu ┆ dka ┆ --- ┆ cni ┆ str ┆ --- ┆ stD ┆ --- ┆ Mil ┆ --- ┆ t[s ┆ s_V ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_Z ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_V ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ s_J ┆ o   ┆ Vyu ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yVo ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ yZv ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ Vzn ┆ --- ┆ yus ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ Pru ┆ 0_T ┆ 0_T ┆ 0_C ┆ 0_C ┆ 0_K ┆ 0_K ┆ 0_O ┆ 0_O ┆ 0_O ┆ 0_O ┆ 0_T ┆ 0_T ┆ 1_T ┆ 1_T ┆ 1_C ┆ 1_C ┆ 1_K ┆ 1_K ┆ 1_O ┆ 1_O ┆ 1_O ┆ 1_O ┆ 1_T ┆ 1_T ┆ 2_T ┆ 2_T ┆ 2_C ┆ 2_C ┆ 2_K ┆ 2_K ┆ 2_O ┆ 2_O ┆ 2_O ┆ 2_O ┆ 2_T ┆ 2_T ┆ 3_T ┆ 3_T ┆ 3_C ┆ 3_C ┆ 3_K ┆ 3_K ┆ 3_O ┆ 3_O ┆ 3_O ┆ 3_O ┆ 3_T ┆ 3_T ┆ --- ┆ ust ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ oln ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ vys ┆ yro ┆ omo ┆ ivo ┆ ont │
│ --- ┆ --- ┆ str ┆     ┆     ┆ --- ┆ Pro ┆ Pro ┆ Vyr ┆ Typ ┆ Ver ┆ OBD ┆ Ver ┆ t[s ┆ str ┆ --- ┆ iOz ┆ ru  ┆ tor ┆ r   ┆ by  ┆ vni ┆ --- ┆ niK ┆ ess ┆ Jed ┆ Jed ┆ str ┆ tPl ┆ je  ┆ --- ┆ str ┆ Pro ┆     ┆ str ┆ tc  ┆ str ┆ --- ┆ lis ┆ tr] ┆ ysl ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ aze ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ 193 ┆ --- ┆ ste ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ lno ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ yse ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ etL ┆ str ┆ ten ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ mer ┆ PS_ ┆ PS_ ┆ asA ┆ asA ┆ our ┆ our ┆ tac ┆ tac ┆ tac ┆ tac ┆ epl ┆ epl ┆ PS_ ┆ PS_ ┆ asA ┆ asA ┆ our ┆ our ┆ tac ┆ tac ┆ tac ┆ tac ┆ epl ┆ epl ┆ PS_ ┆ PS_ ┆ asA ┆ asA ┆ our ┆ our ┆ tac ┆ tac ┆ tac ┆ tac ┆ epl ┆ epl ┆ PS_ ┆ PS_ ┆ asA ┆ asA ┆ our ┆ our ┆ tac ┆ tac ┆ tac ┆ tac ┆ epl ┆ epl ┆ str ┆ eni ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ obe ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ ene ┆ bce ┆ log ┆ tno ┆ rol │
│ str ┆ str ┆     ┆     ┆     ┆ str ┆ tok ┆ hli ┆ obc ┆ --- ┆ ze  ┆ --- ┆ zeS ┆ tr] ┆     ┆ str ┆ nac ┆ --- ┆ u   ┆ --- ┆ --- ┆ Reg ┆ str ┆ ont ┆ --- ┆ not ┆ not ┆     ┆ yno ┆ --- ┆ str ┆     ┆ tok ┆     ┆     ┆ --- ┆     ┆ str ┆ t[s ┆     ┆ ede ┆ h_A ┆ h_A ┆ h_C ┆ h_C ┆ h_C ┆ h_C ┆ h_E ┆ h_E ┆ h_E ┆ h_E ┆ h_F ┆ h_F ┆ h_H ┆ h_H ┆ h_M ┆ h_M ┆ h_O ┆ h_O ┆ h_O ┆ h_O ┆ h_S ┆ h_S ┆ t_A ┆ t_A ┆ t_B ┆ t_B ┆ t_C ┆ t_C ┆ t_D ┆ t_D ┆ t_E ┆ t_E ┆ t_E ┆ t_E ┆ t_F ┆ t_F ┆ t_M ┆ t_M ┆ t_N ┆ t_N ┆ t_N ┆ t_N ┆ t_R ┆ t_R ┆ 9_A ┆ 9_A ┆ 9_B ┆ 9_B ┆ 9_C ┆ 9_C ┆ 9_C ┆ 9_C ┆ 9_C ┆ 9_C ┆ 9_D ┆ 9_D ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_E ┆ 9_F ┆ 9_F ┆ 9_H ┆ 9_H ┆ 9_M ┆ 9_M ┆ 9_N ┆ 9_N ┆ 9_N ┆ 9_N ┆ 9_S ┆ 9_S ┆ str ┆ ni  ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ bez ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆ imi ┆     ┆ i   ┆ _TP ┆ _TP ┆ _Ca ┆ _Ca ┆ _Ko ┆ _Ko ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Ot ┆ _Te ┆ _Te ┆ Hod ┆ Vys ┆ kce ┆ kce ┆ ivo ┆ ivo ┆ kyP ┆ kyP ┆ kyV ┆ kyV ┆ ota ┆ ota ┆ Hod ┆ Vys ┆ kce ┆ kce ┆ ivo ┆ ivo ┆ kyP ┆ kyP ┆ kyV ┆ kyV ┆ ota ┆ ota ┆ Hod ┆ Vys ┆ kce ┆ kce ┆ ivo ┆ ivo ┆ kyP ┆ kyP ┆ kyV ┆ kyV ┆ ota ┆ ota ┆ Hod ┆ Vys ┆ kce ┆ kce ┆ ivo ┆ ivo ┆ kyP ┆ kyP ┆ kyV ┆ kyV ┆ ota ┆ ota ┆     ┆ --- ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ zne ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _HC ┆ _HC ┆ _HC ┆ _HC ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _NO ┆ _NO ┆ _O2 ┆ _O2 ┆ _TP ┆ _TP ┆ --- ┆ ace ┆ st  ┆ a   │
│     ┆     ┆     ┆     ┆     ┆     ┆ olu ┆ dky ┆ e   ┆ str ┆ --- ┆ str ┆ oft ┆     ┆     ┆     ┆ eni ┆ str ┆ --- ┆ str ┆ str ┆ ist ┆     ┆ rol ┆ str ┆ ka  ┆ kaS ┆     ┆ veh ┆ str ┆     ┆     ┆ ol  ┆     ┆     ┆ str ┆     ┆     ┆ tr] ┆     ┆ k   ┆ C_P ┆ C_O ┆ AT- ┆ AT- ┆ OMP ┆ OMP ┆ GR- ┆ GR- ┆ VAP ┆ VAP ┆ UEL ┆ UEL ┆ CAT ┆ CAT ┆ ISF ┆ ISF ┆ 2S- ┆ 2S- ┆ 2S- ┆ 2S- ┆ AS_ ┆ AS_ ┆ C_P ┆ C_O ┆ OOS ┆ OOS ┆ OMP ┆ OMP ┆ PF_ ┆ PF_ ┆ GR- ┆ GR- ┆ GS_ ┆ GS_ ┆ UEL ┆ UEL ┆ ISF ┆ ISF ┆ MHC ┆ MHC ┆ OX_ ┆ OX_ ┆ ESE ┆ ESE ┆ C_P ┆ C_O ┆ OOS ┆ OOS ┆ AT- ┆ AT- ┆ OLD ┆ OLD ┆ OMP ┆ OMP ┆ PF_ ┆ PF_ ┆ GR- ┆ GR- ┆ GS- ┆ GS- ┆ GS- ┆ GS- ┆ VAP ┆ VAP ┆ UEL ┆ UEL ┆ CAT ┆ CAT ┆ ISF ┆ ISF ┆ M-H ┆ M-H ┆ OX_ ┆ OX_ ┆ AS_ ┆ AS_ ┆     ┆ --- ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ ne_ ┆ CO_ ┆ CO_ ┆ CO_ ┆ CO_ ┆ CO2 ┆ CO2 ┆ COC ┆ COC ┆ HC_ ┆ HC_ ┆ HC_ ┆ HC_ ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ N_M ┆ N_M ┆ N_M ┆ N_M ┆ N_H ┆ N_V ┆ NOX ┆ NOX ┆ O2_ ┆ O2_ ┆ TPS ┆ TPS ┆ t_O ┆ t_O ┆ t_O ┆ t_O ┆ t_O ┆ t_O ┆ t_O ┆ t_O ┆ t_C ┆ t_C ┆ t_K ┆ t_K ┆ t_K ┆ t_K ┆     ┆ --- ┆ S_H ┆ S_V ┆ sAk ┆ sAk ┆ uri ┆ uri ┆ ack ┆ ack ┆ ack ┆ ack ┆ plo ┆ plo ┆ not ┆ led ┆ ler ┆ ler ┆ st_ ┆ st_ ┆ reb ┆ reb ┆ oln ┆ oln ┆ _Ho ┆ _Vy ┆ not ┆ led ┆ ler ┆ ler ┆ st_ ┆ st_ ┆ reb ┆ reb ┆ oln ┆ oln ┆ _Ho ┆ _Vy ┆ not ┆ led ┆ ler ┆ ler ┆ st_ ┆ st_ ┆ reb ┆ reb ┆ oln ┆ oln ┆ _Ho ┆ _Vy ┆ not ┆ led ┆ ler ┆ ler ┆ st_ ┆ st_ ┆ reb ┆ reb ┆ oln ┆ oln ┆ _Ho ┆ _Vy ┆     ┆ str ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _CO ┆ _HC ┆ _HC ┆ _HC ┆ _HC ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _LA ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _N_ ┆ _NO ┆ _NO ┆ _O2 ┆ _O2 ┆ _TP ┆ _TP ┆ _Ma ┆ _Ma ┆ _Ho ┆ _Vy ┆ 2_H ┆ 2_V ┆ COO ┆ COO ┆ _Ma ┆ _Ma ┆ _Ho ┆ _Vy ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ Min ┆ Min ┆ Max ┆ Max ┆ Hod ┆ Vys ┆ X_H ┆ X_V ┆ _Ho ┆ _Vy ┆ S_H ┆ S_V ┆ str ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆ str ┆     ┆ war ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ rac ┆     ┆ a   ┆     ┆ --- ┆ tav ┆     ┆ oZa ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ odp ┆ tes ┆ FUN ┆ FUN ┆ _Po ┆ _Ot ┆ VVT ┆ VVT ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ FUN ┆ FUN ┆ HEA ┆ HEA ┆ Pod ┆ Ote ┆ odp ┆ tes ┆ T_P ┆ T_O ┆ _Po ┆ _Ot ┆ Pod ┆ Ote ┆ VVT ┆ VVT ┆ Pod ┆ Ote ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ Pod ┆ Ote ┆ RVE ┆ RVE ┆ odp ┆ tes ┆ T_P ┆ T_O ┆ FUN ┆ FUN ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ Pod ┆ Ote ┆ VVT ┆ VVT ┆ FUN ┆ FUN ┆ HEA ┆ HEA ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ _Po ┆ _Ot ┆ C_P ┆ C_O ┆ Pod ┆ Ote ┆ Pod ┆ Ote ┆     ┆ str ┆ CO_ ┆ CO_ ┆ CO_ ┆ CO_ ┆ CO2 ┆ CO2 ┆ COC ┆ COC ┆ HC_ ┆ HC_ ┆ HC_ ┆ HC_ ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ LAM ┆ N_M ┆ N_M ┆ N_M ┆ N_M ┆ N_H ┆ N_V ┆ NOX ┆ NOX ┆ O2_ ┆ O2_ ┆ TPS ┆ TPS ┆ Max ┆ Max ┆ Hod ┆ Vys ┆ _Ho ┆ _Vy ┆ OOR ┆ OOR ┆ Max ┆ Max ┆ Hod ┆ Vys ┆ BDA ┆ BDA ┆ BDA ┆ BDA ┆ BDA ┆ BDA ┆ in_ ┆ in_ ┆ ax_ ┆ ax_ ┆ odn ┆ ysl ┆ _Ho ┆ _Vy ┆ Hod ┆ Vys ┆ _Ho ┆ _Vy ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ tac ┆ asA ┆ asA ┆ our ┆ our ┆ our ┆ our ┆     ┆ str ┆ odn ┆ ysl ┆ cel ┆ cel ┆ vos ┆ vos ┆ yPr ┆ yPr ┆ yVo ┆ yVo ┆ ta_ ┆ ta_ ┆ a   ┆ ek  ┆ ace ┆ ace ┆ Hod ┆ Vys ┆ eho ┆ eho ┆ obe ┆ obe ┆ dno ┆ sle ┆ a   ┆ ek  ┆ ace ┆ ace ┆ Hod ┆ Vys ┆ eho ┆ eho ┆ obe ┆ obe ┆ dno ┆ sle ┆ a   ┆ ek  ┆ ace ┆ ace ┆ Hod ┆ Vys ┆ eho ┆ eho ┆ obe ┆ obe ┆ dno ┆ sle ┆ a   ┆ ek  ┆ ace ┆ ace ┆ Hod ┆ Vys ┆ eho ┆ eho ┆ obe ┆ obe ┆ dno ┆ sle ┆     ┆     ┆ _Ma ┆ _Ma ┆ _Ho ┆ _Vy ┆ 2_H ┆ 2_V ┆ COO ┆ COO ┆ _Ma ┆ _Ma ┆ _Ho ┆ _Vy ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ MBD ┆ Min ┆ Min ┆ Max ┆ Max ┆ Hod ┆ Vys ┆ X_H ┆ X_V ┆ _Ho ┆ _Vy ┆ S_H ┆ S_V ┆ x_H ┆ x_R ┆ dno ┆ sle ┆ odn ┆ ysl ┆ R_H ┆ R_V ┆ x_H ┆ x_R ┆ dno ┆ sle ┆ A_M ┆ A_M ┆ A_M ┆ A_M ┆ A_H ┆ A_V ┆ _Ho ┆ _Ru ┆ _Ho ┆ _Ru ┆ not ┆ led ┆ odn ┆ ysl ┆ dno ┆ sle ┆ odn ┆ ysl ┆     ┆ str ┆ str ┆ str │

(20174632, 321)

,CisloProtokolu,DatumProhlidky,StaniceCislo,Zahajeni,Ukonceni,OdpovednaOsoba,Prohlidka_CisloProtokolu,Prohlidka_DatumProhlidky,MericiPristroj_Vyrobce,MericiPristroj_Typ,...,Plyn_OtackyZvysene_NOX_Hodnota,Plyn_OtackyZvysene_NOX_Vysledek,Plyn_OtackyZvysene_O2_Hodnota,Plyn_OtackyZvysene_O2_Vysledek,Plyn_OtackyZvysene_TPS_Hodnota,Plyn_OtackyZvysene_TPS_Vysledek,Plyn_Nadrz_Vyrobce,Plyn_Nadrz_Homologace,Plyn_Nadrz_Zivotnost,Plyn_Nadrz_Kontrola
0,CZ-420930-19-01-0001,2019-01-01,420930,2019-01-01T14:43:55.0200000+01:00,2019-01-01T15:06:04.3900000+01:00,47287,CZ-420930-19-01-0001,2019-01-01T14:51:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
1,CZ-520406-19-01-0001,2019-01-01,520406,2019-01-01T15:22:33.2900000+01:00,2019-01-01T15:39:51.5500000+01:00,16835,CZ-520406-19-01-0001,2019-01-01T15:27:00,AVL DiTEST GmbH,AVL DiSmoke 480,...,None,None,None,None,None,None,None,None,None,None
2,CZ-170901-23-01-0002,2023-01-01,170901,2023-01-01T19:42:08.8770000+01:00,2023-01-01T19:53:03.3100000+01:00,89493,CZ-170901-23-01-0002,2023-01-01T19:50:00,MAHLE,OPA-100,...,None,None,None,None,None,None,None,None,None,None
3,CZ-480811-23-01-0001,2023-01-01,480811,2023-01-01T12:22:13.5700000+01:00,2023-01-01T12:36:18.7000000+01:00,36479,CZ-480811-23-01-0001,2023-01-01T12:33:00,MAHLE,OPA-100,...,None,None,None,None,None,None,None,None,None,None
4,CZ-420221-23-01-0001,2023-01-01,420221,2023-01-01T16:07:06.1270000+01:00,2023-01-01T16:17:16.0300000+01:00,44365,CZ-420221-23-01-0001,2023-01-01T16:17:00,ACTIA CZ s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
5,CZ-420221-23-01-0003,2023-01-01,420221,2023-01-01T16:57:28.1900000+01:00,2023-01-01T17:06:11.8300000+01:00,44365,CZ-420221-23-01-0003,2023-01-01T17:05:00,ACTIA CZ s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
6,CZ-170901-23-01-0001,2023-01-01,170901,2023-01-01T19:24:30.3070000+01:00,2023-01-01T19:36:25.5270000+01:00,89493,CZ-170901-23-01-0001,2023-01-01T19:32:00,MAHLE,OPA-100,...,None,None,None,None,None,None,None,None,None,None
7,CZ-420221-23-01-0004,2023-01-01,420221,2023-01-01T17:26:23.7170000+01:00,2023-01-01T17:41:10.1600000+01:00,44365,CZ-420221-23-01-0004,2023-01-01T17:40:00,ACTIA CZ s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
8,CZ-520406-24-01-0001,2024-01-01,520406,2024-01-01T11:31:17.2900000+01:00,2024-01-01T11:48:07.5200000+01:00,1308,CZ-520406-24-01-0001,2024-01-01T11:38:00,AVL DiTEST GmbH,AVL Gas 1000,...,None,None,None,None,None,None,None,None,None,None
9,CZ-480811-24-01-0001,2024-01-01,480811,2024-01-01T16:22:23.1070000+01:00,2024-01-01T16:36:09.9300000+01:00,36479,CZ-480811-24-01-0001,2024-01-01T16:31:00,MAHLE,OPA-100,...,None,None,None,None,None,None,None,None,None,None
10,CZ-571206-24-01-0001,2024-01-01,571206,2024-01-01T17:05:01.8300000+01:00,2024-01-01T17:14:55.7900000+01:00,58519,CZ-571206-24-01-0001,2024-01-01T17:12:00,MAHLE,OPA-100,...,None,None,None,None,None,None,None,None,None,None
11,CZ-420221-25-01-0001,2025-01-01,420221,2025-01-01T17:04:29.5830000+01:00,2025-01-01T17:27:04.9700000+01:00,44365,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
12,CZ-420221-25-01-0002,2025-01-01,420221,2025-01-01T17:31:04.3500000+01:00,2025-01-01T17:41:51.6070000+01:00,44365,CZ-420221-25-01-0002,2025-01-01T17:41:00,ATAL s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
13,CZ-420221-25-01-0003,2025-01-01,420221,2025-01-01T18:11:52.5230000+01:00,2025-01-01T18:19:21.5000000+01:00,44365,CZ-420221-25-01-0003,2025-01-01T18:18:00,ATAL s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
14,CZ-420221-25-01-0004,2025-01-01,420221,2025-01-01T18:23:05.6300000+01:00,2025-01-01T18:33:24.5300000+01:00,44365,CZ-420221-25-01-0004,2025-01-01T18:33:00,ACTIA CZ s.r.o.,ATAL505,...,None,None,None,None,None,None,None,None,None,None
15,CZ-420221-25-01-0005,2025-01-01,420221,2025-01-01T18:37:11.5970000+01:00,2025-01-01T18:58:17.6570000+01:00,44365,CZ-420221-25-01-0005,2025-01-01T18:58:00,ATAL s.r.o.,AT605,...,None,None,None,None,None,None,None,None,None,None
16,CZ-420107-19-02-0012,2019-02-01,420107,2019-02-01T16:23:46.0770000+01:00,2019-02-01T16:43:27.8830000+01:00,50929,CZ-420107-19-02-0012,2019-02-01T16:43:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
17,CZ-460214-19-02-0056,2019-02-01,460214,2019-02-01T19:16:29.7870000+01:00,2019-02-01T19:33:06.5370000+01:00,37937,CZ-460214-19-02-0056,2019-02-01T19:20:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
18,CZ-450620-19-02-0004,2019-02-01,450620,2019-02-01T16:26:32.7170000+01:00,2019-02-01T16:37:46.1970000+01:00,37581,CZ-450620-19-02-0004,2019-02-01T16:36:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
19,CZ-480714-19-02-0036,2019-02-01,480714,2019-02-01T15:35:24.7570000+01:00,2019-02-01T15:56:21.3200000+01:00,45183,CZ-480714-19-02-0036,2019-02-01T15:46:00,BOSCH,BEA060,...,None,None,None,None,None,None,None,None,None,None
20,CZ-480756-19-02-0023,2019-02-01,480756,2019-02-01T16:22:35.0630000+01:00,2019-02-01T16:31:04.0170000+01:00,37311,CZ-480756-19-02-0023,2019-02-01T16:19:01,BOSCH,BEA050,...,None,None,None,None,None,None,None,None,None,None
21,CZ-560613-19-02-0024,2019-02-01,560613,2019-02-01T16:36:37.4330000+01:00,2019-02-01T16:47:13.6700000+01:00,21187,CZ-560613-19-02-0024,2019-02-01T16:36:39,AVL DiTEST GmbH,AVL DiSmoke 480,...,None,None,None,None,None,None,None,None,None,None
22,CZ-430427-19-02-0019,2019-02-01,430427,2019-02-01T16:14:29.6970000+01:00,2019-02-01T16:28:55.8530000+01:00,41755,CZ-430427-19-02-0019,2019-02-01T16:23:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
23,CZ-540514-19-02-0127,2019-02-01,540514,2019-02-01T15:42:01.6330000+01:00,2019-02-01T15:51:11.8400000+01:00,34773,CZ-540514-19-02-0127,2019-02-01T15:45:00,AVL DiTEST GmbH,AVL DiSmoke 480,...,None,None,None,None,None,None,None,None,None,None
24,CZ-540514-19-02-0128,2019-02-01,540514,2019-02-01T16:17:18.4970000+01:00,2019-02-01T16:29:29.7070000+01:00,10599,CZ-540514-19-02-0128,2019-02-01T16:21:00,AVL DiTEST GmbH,AVL Gas 1000,...,None,None,None,None,None,None,None,None,None,None
25,CZ-460257-19-02-0025,2019-02-01,460257,2019-02-01T16:08:35.0430000+01:00,2019-02-01T16:19:28.7500000+01:00,43903,CZ-460257-19-02-0025,2019-02-01T16:19:00,ActiaCZ,AT505,...,None,None,None,None,None,None,None,None,None,None
26,CZ-460257-19-02-0024,2019-02-01,460257,2019-02-01T15:52:51.6430000+01:00,2019-02-01T16:00:57.0730000+01:00,43903,CZ-460257-19-02-0024,2019-02-01T16:00:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
27,CZ-550309-19-02-0015,2019-02-01,550309,2019-02-01T15:45:52.0600000+01:00,2019-02-01T15:56:35.1200000+01:00,2545,CZ-550309-19-02-0015,2019-02-01T15:53:00,BRAIN BEE,AGS-200,...,None,None,None,None,None,None,None,None,None,None
28,CZ-440709-19-02-0045,2019-02-01,440709,2019-02-01T16:28:22.9470000+01:00,2019-02-01T16:33:18.4470000+01:00,2399,CZ-440709-19-02-0045,2019-02-01T16:30:00,Bosch,BEA050,...,None,None,None,None,None,None,None,None,None,None
29,CZ-440709-19-02-0046,2019-02-01,440709,2019-02-01T16:57:31.2730000+01:00,2019-02-01T17:02:13.2330000+01:00,34841,CZ-440709-19-02-0046,2019-02-01T16:58:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
30,CZ-440709-19-02-0044,2019-02-01,440709,2019-02-01T16:14:13.1830000+01:00,2019-02-01T16:19:15.3230000+01:00,2399,CZ-440709-19-02-0044,2019-02-01T16:15:00,Bosch,BEA050,...,None,None,None,None,None,None,None,None,None,None
31,CZ-440709-19-02-0048,2019-02-01,440709,2019-02-01T17:56:13.8670000+01:00,2019-02-01T17:59:10.6870000+01:00,34841,CZ-440709-19-02-0048,2019-02-01T17:56:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
32,CZ-410617-19-02-0020,2019-02-01,410617,2019-02-01T16:25:47.1530000+01:00,2019-02-01T16:34:04.4630000+01:00,41223,CZ-410617-19-02-0020,2019-02-01T16:25:00,Bosch,BEA070,...,None,None,None,None,None,None,None,None,None,None
33,CZ-460804-19-02-0006,2019-02-01,460804,2019-02-01T16:12:15.5100000+01:00,2019-02-01T16:35:21.2970000+01:00,40267,CZ-460804-19-02-0006,2019-02-01T16:19:03,BOSCH,BEA050,...,None,None,None,None,None,None,None,None,None,None
34,CZ-410945-19-02-0039,2019-02-01,410945,2019-02-01T15:45:23.9100000+01:00,2019-02-01T15:56:16.7700000+01:00,36697,CZ-410945-19-02-0039,2019-02-01T15:51:00,Bosch,BEA050,...,None,None,None,None,None,None,None,None,None,None
35,CZ-420620-19-02-0041,2019-02-01,420620,2019-02-01T16:16:02.4270000+01:00,2019-02-01T16:27:54.9130000+01:00,2185,CZ-420620-19-02-0041,2019-02-01T16:21:00,Bosch,BEA050,...,None,None,None,None,None,None,None,None,None,None
36,CZ-450808-19-02-0013,2019-02-01,450808,2019-02-01T16:17:36.6730000+01:00,2019-02-01T16:44:24.2330000+01:00,36827,CZ-450808-19-02-0013,2019-02-01T16:34:00,Bosch,BEA070,...,None,None,None,None,None,None,None,None,None,None
37,CZ-521207-19-02-0021,2019-02-01,521207,2019-02-01T18:06:51.4970000+01:00,2019-02-01T18:18:18.4470000+01:00,40937,CZ-521207-19-02-0021,2019-02-01T18:15:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
38,CZ-521207-19-02-0020,2019-02-01,521207,2019-02-01T17:38:28.2830000+01:00,2019-02-01T17:50:49.0100000+01:00,40527,CZ-521207-19-02-0020,2019-02-01T17:44:00,ActiaCZ,AT505,...,None,None,None,None,None,None,None,None,None,None
39,CZ-521207-19-02-0019,2019-02-01,521207,2019-02-01T17:03:02.0700000+01:00,2019-02-01T17:11:06.8570000+01:00,40937,CZ-521207-19-02-0019,2019-02-01T17:08:00,ActiaCZ,AT505,...,None,None,None,None,None,None,None,None,None,None
40,CZ-521207-19-02-0018,2019-02-01,521207,2019-02-01T16:49:16.7500000+01:00,2019-02-01T16:59:33.1570000+01:00,40527,CZ-521207-19-02-0018,2019-02-01T16:53:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
41,CZ-480512-19-02-0029,2019-02-01,480512,2019-02-01T16:42:38.1530000+01:00,2019-02-01T16:51:43.5530000+01:00,45165,CZ-480512-19-02-0029,2019-02-01T16:50:00,ActiaCZ,AT505,...,None,None,None,None,None,None,None,None,None,None
42,CZ-460903-19-02-0003,2019-02-01,460903,2019-02-01T16:07:35.6370000+01:00,2019-02-01T16:37:33.3730000+01:00,40305,CZ-460903-19-02-0003,2019-02-01T16:32:00,BRISK,JT283A,...,None,None,None,None,None,None,None,None,None,None
43,CZ-470538-19-02-0001,2019-02-01,470538,2019-02-01T19:05:56.7130000+01:00,2019-02-01T19:29:08.0170000+01:00,43181,CZ-470538-19-02-0001,2019-02-01T19:38:00,MAHA,MDO-2,...,None,None,None,None,None,None,None,None,None,None
44,CZ-550606-19-02-0025,2019-02-01,550606,2019-02-01T16:26:00.1500000+01:00,2019-02-01T16:38:52.2100000+01:00,41229,CZ-550606-19-02-0025,2019-02-01T16:38:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
45,CZ-471025-19-02-0020,2019-02-01,471025,2019-02-01T15:46:41.4670000+01:00,2019-02-01T16:03:17.4100000+01:00,37829,CZ-471025-19-02-0020,2019-02-01T15:54:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
46,CZ-460257-19-02-0026,2019-02-01,460257,2019-02-01T16:36:58.5200000+01:00,2019-02-01T17:23:01.4400000+01:00,43903,CZ-460257-19-02-0026,2019-02-01T17:22:00,ActiaCZ,AT605,...,None,None,None,None,None,None,None,None,None,None
47,CZ-460214-19-02-0055,2019-02-01,460214,2019-02-01T18:49:46.7770000+01:00,2019-02-01T19:02:41.9170000+01:00,37937,CZ-460214-19-02-0055,2019-02-01T18:51:00,Bosch,BEA055,...,None,None,None,None,None,None,None,None,None,None
48,CZ-420620-19-02-0042,2019-02-01,420620,2019-02-01T17:43:07.1900000+01:00,2019-02-01T17:49:42.1930000+01:00,2185,CZ-420620-19-02-0042,2019-02-01T17:45:00,Bosch,RTM430,...,None,None,None,None,None,None,None,None,None,None
49,CZ-570711-19-02-0033,2019-02-01,570711,2019-02-01T17:09:10.6600000+01:00,2019-02-01T17:12:24.4000000+01:00,50219,CZ-570711-19-02-0033,2019-02-01T17:10:08,---,---,...,None,None,None,None,None,None,None,None,None,None

: